<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Grupo', 'doctrine');

/**
 * BaseGrupo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_grupo
 * @property string $no_grupo
 * @property string $id_curso
 * @property string $nombre
 * @property integer $id_tipo
 * @property timestamp $fecha_creado
 * @property Tipo $Tipo
 * @property Doctrine_Collection $Estudiante
 * 
 * @method integer             getIdGrupo()      Returns the current record's "id_grupo" value
 * @method string              getNoGrupo()      Returns the current record's "no_grupo" value
 * @method string              getIdCurso()      Returns the current record's "id_curso" value
 * @method string              getNombre()       Returns the current record's "nombre" value
 * @method integer             getIdTipo()       Returns the current record's "id_tipo" value
 * @method timestamp           getFechaCreado()  Returns the current record's "fecha_creado" value
 * @method Tipo                getTipo()         Returns the current record's "Tipo" value
 * @method Doctrine_Collection getEstudiante()   Returns the current record's "Estudiante" collection
 * @method Grupo               setIdGrupo()      Sets the current record's "id_grupo" value
 * @method Grupo               setNoGrupo()      Sets the current record's "no_grupo" value
 * @method Grupo               setIdCurso()      Sets the current record's "id_curso" value
 * @method Grupo               setNombre()       Sets the current record's "nombre" value
 * @method Grupo               setIdTipo()       Sets the current record's "id_tipo" value
 * @method Grupo               setFechaCreado()  Sets the current record's "fecha_creado" value
 * @method Grupo               setTipo()         Sets the current record's "Tipo" value
 * @method Grupo               setEstudiante()   Sets the current record's "Estudiante" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Hender Orlando Puello Rincón
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGrupo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('grupo');
        $this->hasColumn('id_grupo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('no_grupo', 'string', 3, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('id_curso', 'string', 2, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('nombre', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('id_tipo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('fecha_creado', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tipo', array(
             'local' => 'id_tipo',
             'foreign' => 'id_tipo'));

        $this->hasMany('Estudiante', array(
             'local' => 'id_grupo',
             'foreign' => 'id_grupo'));
    }
}