<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Estudiante', 'doctrine');

/**
 * BaseEstudiante
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_curso
 * @property integer $id_estudiante
 * @property integer $cod_curso
 * @property timestamp $fecha_creado
 * @property CursosGrado $CursosGrado
 * @property Persona $Persona
 * 
 * @method integer     getIdCurso()       Returns the current record's "id_curso" value
 * @method integer     getIdEstudiante()  Returns the current record's "id_estudiante" value
 * @method integer     getCodCurso()      Returns the current record's "cod_curso" value
 * @method timestamp   getFechaCreado()   Returns the current record's "fecha_creado" value
 * @method CursosGrado getCursosGrado()   Returns the current record's "CursosGrado" value
 * @method Persona     getPersona()       Returns the current record's "Persona" value
 * @method Estudiante  setIdCurso()       Sets the current record's "id_curso" value
 * @method Estudiante  setIdEstudiante()  Sets the current record's "id_estudiante" value
 * @method Estudiante  setCodCurso()      Sets the current record's "cod_curso" value
 * @method Estudiante  setFechaCreado()   Sets the current record's "fecha_creado" value
 * @method Estudiante  setCursosGrado()   Sets the current record's "CursosGrado" value
 * @method Estudiante  setPersona()       Sets the current record's "Persona" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Hender Orlando Puello Rincón
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstudiante extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estudiante');
        $this->hasColumn('id_curso', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_estudiante', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('cod_curso', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('fecha_creado', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CursosGrado', array(
             'local' => 'id_curso',
             'foreign' => 'id_curso_grado'));

        $this->hasOne('Persona', array(
             'local' => 'id_estudiante',
             'foreign' => 'id_persona'));
    }
}