<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ArchivosEntidadEducativa', 'doctrine');

/**
 * BaseArchivosEntidadEducativa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_entidad_educativa
 * @property integer $id_archivo
 * @property integer $id_tipo_uso
 * @property timestamp $fecha_creado
 * @property EntidadEducativa $EntidadEducativa
 * @property Archivo $Archivo
 * @property Tipo $Tipo
 * @property Doctrine_Collection $Candidato
 * 
 * @method integer                  getIdEntidadEducativa()   Returns the current record's "id_entidad_educativa" value
 * @method integer                  getIdArchivo()            Returns the current record's "id_archivo" value
 * @method integer                  getIdTipoUso()            Returns the current record's "id_tipo_uso" value
 * @method timestamp                getFechaCreado()          Returns the current record's "fecha_creado" value
 * @method EntidadEducativa         getEntidadEducativa()     Returns the current record's "EntidadEducativa" value
 * @method Archivo                  getArchivo()              Returns the current record's "Archivo" value
 * @method Tipo                     getTipo()                 Returns the current record's "Tipo" value
 * @method Doctrine_Collection      getCandidato()            Returns the current record's "Candidato" collection
 * @method ArchivosEntidadEducativa setIdEntidadEducativa()   Sets the current record's "id_entidad_educativa" value
 * @method ArchivosEntidadEducativa setIdArchivo()            Sets the current record's "id_archivo" value
 * @method ArchivosEntidadEducativa setIdTipoUso()            Sets the current record's "id_tipo_uso" value
 * @method ArchivosEntidadEducativa setFechaCreado()          Sets the current record's "fecha_creado" value
 * @method ArchivosEntidadEducativa setEntidadEducativa()     Sets the current record's "EntidadEducativa" value
 * @method ArchivosEntidadEducativa setArchivo()              Sets the current record's "Archivo" value
 * @method ArchivosEntidadEducativa setTipo()                 Sets the current record's "Tipo" value
 * @method ArchivosEntidadEducativa setCandidato()            Sets the current record's "Candidato" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Hender Orlando Puello Rincón
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArchivosEntidadEducativa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('archivos_entidad_educativa');
        $this->hasColumn('id_entidad_educativa', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_archivo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_tipo_uso', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('fecha_creado', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('EntidadEducativa', array(
             'local' => 'id_entidad_educativa',
             'foreign' => 'id_entidad_educativa'));

        $this->hasOne('Archivo', array(
             'local' => 'id_archivo',
             'foreign' => 'id_archivo'));

        $this->hasOne('Tipo', array(
             'local' => 'id_tipo_uso',
             'foreign' => 'id_tipo'));

        $this->hasMany('Candidato', array(
             'local' => 'id_archivo',
             'foreign' => 'foto'));
    }
}