<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Grado', 'doctrine');

/**
 * BaseGrado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_grado
 * @property string $abreviatura
 * @property string $nombre
 * @property timestamp $fecha_creado
 * @property Doctrine_Collection $GradoEntidadEducativa
 * 
 * @method integer             getIdGrado()               Returns the current record's "id_grado" value
 * @method string              getAbreviatura()           Returns the current record's "abreviatura" value
 * @method string              getNombre()                Returns the current record's "nombre" value
 * @method timestamp           getFechaCreado()           Returns the current record's "fecha_creado" value
 * @method Doctrine_Collection getGradoEntidadEducativa() Returns the current record's "GradoEntidadEducativa" collection
 * @method Grado               setIdGrado()               Sets the current record's "id_grado" value
 * @method Grado               setAbreviatura()           Sets the current record's "abreviatura" value
 * @method Grado               setNombre()                Sets the current record's "nombre" value
 * @method Grado               setFechaCreado()           Sets the current record's "fecha_creado" value
 * @method Grado               setGradoEntidadEducativa() Sets the current record's "GradoEntidadEducativa" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Hender Orlando Puello Rincón
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGrado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('grado');
        $this->hasColumn('id_grado', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('abreviatura', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('nombre', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('fecha_creado', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('GradoEntidadEducativa', array(
             'local' => 'id_grado',
             'foreign' => 'id_grado'));
    }
}