<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GradoEntidadEducativa', 'doctrine');

/**
 * BaseGradoEntidadEducativa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_grado
 * @property integer $id_entidad_educativa
 * @property timestamp $fecha_creado
 * @property Grado $Grado
 * @property EntidadEducativa $EntidadEducativa
 * @property Doctrine_Collection $CursosGrado
 * @property Doctrine_Collection $CursosGrado_3
 * 
 * @method integer               getIdGrado()              Returns the current record's "id_grado" value
 * @method integer               getIdEntidadEducativa()   Returns the current record's "id_entidad_educativa" value
 * @method timestamp             getFechaCreado()          Returns the current record's "fecha_creado" value
 * @method Grado                 getGrado()                Returns the current record's "Grado" value
 * @method EntidadEducativa      getEntidadEducativa()     Returns the current record's "EntidadEducativa" value
 * @method Doctrine_Collection   getCursosGrado()          Returns the current record's "CursosGrado" collection
 * @method Doctrine_Collection   getCursosGrado3()         Returns the current record's "CursosGrado_3" collection
 * @method GradoEntidadEducativa setIdGrado()              Sets the current record's "id_grado" value
 * @method GradoEntidadEducativa setIdEntidadEducativa()   Sets the current record's "id_entidad_educativa" value
 * @method GradoEntidadEducativa setFechaCreado()          Sets the current record's "fecha_creado" value
 * @method GradoEntidadEducativa setGrado()                Sets the current record's "Grado" value
 * @method GradoEntidadEducativa setEntidadEducativa()     Sets the current record's "EntidadEducativa" value
 * @method GradoEntidadEducativa setCursosGrado()          Sets the current record's "CursosGrado" collection
 * @method GradoEntidadEducativa setCursosGrado3()         Sets the current record's "CursosGrado_3" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Hender Orlando Puello Rincón
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGradoEntidadEducativa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('grado_entidad_educativa');
        $this->hasColumn('id_grado', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_entidad_educativa', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('fecha_creado', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Grado', array(
             'local' => 'id_grado',
             'foreign' => 'id_grado'));

        $this->hasOne('EntidadEducativa', array(
             'local' => 'id_entidad_educativa',
             'foreign' => 'id_entidad_educativa'));

        $this->hasMany('CursosGrado', array(
             'local' => 'id_grado',
             'foreign' => 'id_grado'));

        $this->hasMany('CursosGrado as CursosGrado_3', array(
             'local' => 'id_entidad_educativa',
             'foreign' => 'id_entidad_educativa'));
    }
}