<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EntidadEducativa', 'doctrine');

/**
 * BaseEntidadEducativa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_entidad_educativa
 * @property string $nombre
 * @property string $abreviatura
 * @property integer $id_tipo_entidad_educativa
 * @property timestamp $fecha_creado
 * @property Tipo $Tipo
 * @property Doctrine_Collection $ArchivosEntidadEducativa
 * @property Doctrine_Collection $GradoEntidadEducativa
 * @property Doctrine_Collection $MesaEntidadEducativa
 * @property Doctrine_Collection $PerfilesPersona
 * 
 * @method integer             getIdEntidadEducativa()        Returns the current record's "id_entidad_educativa" value
 * @method string              getNombre()                    Returns the current record's "nombre" value
 * @method string              getAbreviatura()               Returns the current record's "abreviatura" value
 * @method integer             getIdTipoEntidadEducativa()    Returns the current record's "id_tipo_entidad_educativa" value
 * @method timestamp           getFechaCreado()               Returns the current record's "fecha_creado" value
 * @method Tipo                getTipo()                      Returns the current record's "Tipo" value
 * @method Doctrine_Collection getArchivosEntidadEducativa()  Returns the current record's "ArchivosEntidadEducativa" collection
 * @method Doctrine_Collection getGradoEntidadEducativa()     Returns the current record's "GradoEntidadEducativa" collection
 * @method Doctrine_Collection getMesaEntidadEducativa()      Returns the current record's "MesaEntidadEducativa" collection
 * @method Doctrine_Collection getPerfilesPersona()           Returns the current record's "PerfilesPersona" collection
 * @method EntidadEducativa    setIdEntidadEducativa()        Sets the current record's "id_entidad_educativa" value
 * @method EntidadEducativa    setNombre()                    Sets the current record's "nombre" value
 * @method EntidadEducativa    setAbreviatura()               Sets the current record's "abreviatura" value
 * @method EntidadEducativa    setIdTipoEntidadEducativa()    Sets the current record's "id_tipo_entidad_educativa" value
 * @method EntidadEducativa    setFechaCreado()               Sets the current record's "fecha_creado" value
 * @method EntidadEducativa    setTipo()                      Sets the current record's "Tipo" value
 * @method EntidadEducativa    setArchivosEntidadEducativa()  Sets the current record's "ArchivosEntidadEducativa" collection
 * @method EntidadEducativa    setGradoEntidadEducativa()     Sets the current record's "GradoEntidadEducativa" collection
 * @method EntidadEducativa    setMesaEntidadEducativa()      Sets the current record's "MesaEntidadEducativa" collection
 * @method EntidadEducativa    setPerfilesPersona()           Sets the current record's "PerfilesPersona" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Hender Orlando Puello Rincón
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEntidadEducativa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('entidad_educativa');
        $this->hasColumn('id_entidad_educativa', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('nombre', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 64,
             ));
        $this->hasColumn('abreviatura', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('id_tipo_entidad_educativa', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('fecha_creado', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tipo', array(
             'local' => 'id_tipo_entidad_educativa',
             'foreign' => 'id_tipo'));

        $this->hasMany('ArchivosEntidadEducativa', array(
             'local' => 'id_entidad_educativa',
             'foreign' => 'id_entidad_educativa'));

        $this->hasMany('GradoEntidadEducativa', array(
             'local' => 'id_entidad_educativa',
             'foreign' => 'id_entidad_educativa'));

        $this->hasMany('MesaEntidadEducativa', array(
             'local' => 'id_entidad_educativa',
             'foreign' => 'id_entidad_educativa'));

        $this->hasMany('PerfilesPersona', array(
             'local' => 'id_entidad_educativa',
             'foreign' => 'id_entidad_educativa'));
    }
}