<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Curso', 'doctrine');

/**
 * BaseCurso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_curso
 * @property string $nombre
 * @property string $abreviatura
 * @property timestamp $fecha_creado
 * @property Doctrine_Collection $CursosGrado
 * 
 * @method integer             getIdCurso()      Returns the current record's "id_curso" value
 * @method string              getNombre()       Returns the current record's "nombre" value
 * @method string              getAbreviatura()  Returns the current record's "abreviatura" value
 * @method timestamp           getFechaCreado()  Returns the current record's "fecha_creado" value
 * @method Doctrine_Collection getCursosGrado()  Returns the current record's "CursosGrado" collection
 * @method Curso               setIdCurso()      Sets the current record's "id_curso" value
 * @method Curso               setNombre()       Sets the current record's "nombre" value
 * @method Curso               setAbreviatura()  Sets the current record's "abreviatura" value
 * @method Curso               setFechaCreado()  Sets the current record's "fecha_creado" value
 * @method Curso               setCursosGrado()  Sets the current record's "CursosGrado" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Hender Orlando Puello Rincón
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCurso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('curso');
        $this->hasColumn('id_curso', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('nombre', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('abreviatura', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('fecha_creado', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CursosGrado', array(
             'local' => 'id_curso',
             'foreign' => 'id_curso'));
    }
}