<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Mesa', 'doctrine');

/**
 * BaseMesa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_mesa
 * @property string $nombre
 * @property timestamp $fecha_creado
 * @property Doctrine_Collection $MesaEntidadEducativa
 * 
 * @method integer             getIdMesa()               Returns the current record's "id_mesa" value
 * @method string              getNombre()               Returns the current record's "nombre" value
 * @method timestamp           getFechaCreado()          Returns the current record's "fecha_creado" value
 * @method Doctrine_Collection getMesaEntidadEducativa() Returns the current record's "MesaEntidadEducativa" collection
 * @method Mesa                setIdMesa()               Sets the current record's "id_mesa" value
 * @method Mesa                setNombre()               Sets the current record's "nombre" value
 * @method Mesa                setFechaCreado()          Sets the current record's "fecha_creado" value
 * @method Mesa                setMesaEntidadEducativa() Sets the current record's "MesaEntidadEducativa" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Hender Orlando Puello Rincón
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMesa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mesa');
        $this->hasColumn('id_mesa', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('nombre', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('fecha_creado', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('MesaEntidadEducativa', array(
             'local' => 'id_mesa',
             'foreign' => 'id_mesa'));
    }
}