<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Persona', 'doctrine');

/**
 * BasePersona
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_persona
 * @property integer $tipo_doc_id
 * @property string $nombre
 * @property string $clave
 * @property timestamp $fecha_creado
 * @property Tipo $Tipo
 * @property Doctrine_Collection $Estudiante
 * @property Doctrine_Collection $Jurado
 * @property Doctrine_Collection $PerfilesPersona
 * @property Doctrine_Collection $Votante
 * 
 * @method integer             getIdPersona()       Returns the current record's "id_persona" value
 * @method integer             getTipoDocId()       Returns the current record's "tipo_doc_id" value
 * @method string              getNombre()          Returns the current record's "nombre" value
 * @method string              getClave()           Returns the current record's "clave" value
 * @method timestamp           getFechaCreado()     Returns the current record's "fecha_creado" value
 * @method Tipo                getTipo()            Returns the current record's "Tipo" value
 * @method Doctrine_Collection getEstudiante()      Returns the current record's "Estudiante" collection
 * @method Doctrine_Collection getJurado()          Returns the current record's "Jurado" collection
 * @method Doctrine_Collection getPerfilesPersona() Returns the current record's "PerfilesPersona" collection
 * @method Doctrine_Collection getVotante()         Returns the current record's "Votante" collection
 * @method Persona             setIdPersona()       Sets the current record's "id_persona" value
 * @method Persona             setTipoDocId()       Sets the current record's "tipo_doc_id" value
 * @method Persona             setNombre()          Sets the current record's "nombre" value
 * @method Persona             setClave()           Sets the current record's "clave" value
 * @method Persona             setFechaCreado()     Sets the current record's "fecha_creado" value
 * @method Persona             setTipo()            Sets the current record's "Tipo" value
 * @method Persona             setEstudiante()      Sets the current record's "Estudiante" collection
 * @method Persona             setJurado()          Sets the current record's "Jurado" collection
 * @method Persona             setPerfilesPersona() Sets the current record's "PerfilesPersona" collection
 * @method Persona             setVotante()         Sets the current record's "Votante" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Hender Orlando Puello Rincón
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePersona extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('persona');
        $this->hasColumn('id_persona', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('tipo_doc_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('nombre', 'string', 40, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 40,
             ));
        $this->hasColumn('clave', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('fecha_creado', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tipo', array(
             'local' => 'tipo_doc_id',
             'foreign' => 'id_tipo'));

        $this->hasMany('Estudiante', array(
             'local' => 'id_persona',
             'foreign' => 'id_estudiante'));

        $this->hasMany('Jurado', array(
             'local' => 'id_persona',
             'foreign' => 'id_jurado'));

        $this->hasMany('PerfilesPersona', array(
             'local' => 'id_persona',
             'foreign' => 'id_persona'));

        $this->hasMany('Votante', array(
             'local' => 'id_persona',
             'foreign' => 'id_votante'));
    }
}