<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Tipo', 'doctrine');

/**
 * BaseTipo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_tipo
 * @property string $nombre
 * @property string $descripcion
 * @property timestamp $fecha_creado
 * @property string $objeto
 * @property Doctrine_Collection $ArchivosEntidadEducativa
 * @property Doctrine_Collection $Candidato
 * @property Doctrine_Collection $EntidadEducativa
 * @property Doctrine_Collection $Jurado
 * @property Doctrine_Collection $MesaEntidadEducativa
 * @property Doctrine_Collection $PerfilesPersona
 * @property Doctrine_Collection $Persona
 * @property Doctrine_Collection $Votante
 * 
 * @method integer             getIdTipo()                   Returns the current record's "id_tipo" value
 * @method string              getNombre()                   Returns the current record's "nombre" value
 * @method string              getDescripcion()              Returns the current record's "descripcion" value
 * @method timestamp           getFechaCreado()              Returns the current record's "fecha_creado" value
 * @method string              getObjeto()                   Returns the current record's "objeto" value
 * @method Doctrine_Collection getArchivosEntidadEducativa() Returns the current record's "ArchivosEntidadEducativa" collection
 * @method Doctrine_Collection getCandidato()                Returns the current record's "Candidato" collection
 * @method Doctrine_Collection getEntidadEducativa()         Returns the current record's "EntidadEducativa" collection
 * @method Doctrine_Collection getJurado()                   Returns the current record's "Jurado" collection
 * @method Doctrine_Collection getMesaEntidadEducativa()     Returns the current record's "MesaEntidadEducativa" collection
 * @method Doctrine_Collection getPerfilesPersona()          Returns the current record's "PerfilesPersona" collection
 * @method Doctrine_Collection getPersona()                  Returns the current record's "Persona" collection
 * @method Doctrine_Collection getVotante()                  Returns the current record's "Votante" collection
 * @method Tipo                setIdTipo()                   Sets the current record's "id_tipo" value
 * @method Tipo                setNombre()                   Sets the current record's "nombre" value
 * @method Tipo                setDescripcion()              Sets the current record's "descripcion" value
 * @method Tipo                setFechaCreado()              Sets the current record's "fecha_creado" value
 * @method Tipo                setObjeto()                   Sets the current record's "objeto" value
 * @method Tipo                setArchivosEntidadEducativa() Sets the current record's "ArchivosEntidadEducativa" collection
 * @method Tipo                setCandidato()                Sets the current record's "Candidato" collection
 * @method Tipo                setEntidadEducativa()         Sets the current record's "EntidadEducativa" collection
 * @method Tipo                setJurado()                   Sets the current record's "Jurado" collection
 * @method Tipo                setMesaEntidadEducativa()     Sets the current record's "MesaEntidadEducativa" collection
 * @method Tipo                setPerfilesPersona()          Sets the current record's "PerfilesPersona" collection
 * @method Tipo                setPersona()                  Sets the current record's "Persona" collection
 * @method Tipo                setVotante()                  Sets the current record's "Votante" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Hender Orlando Puello Rincón
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo');
        $this->hasColumn('id_tipo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('nombre', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('fecha_creado', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('objeto', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ArchivosEntidadEducativa', array(
             'local' => 'id_tipo',
             'foreign' => 'id_tipo_uso'));

        $this->hasMany('Candidato', array(
             'local' => 'id_tipo',
             'foreign' => 'id_tipo_eleccion'));

        $this->hasMany('EntidadEducativa', array(
             'local' => 'id_tipo',
             'foreign' => 'id_tipo_entidad_educativa'));

        $this->hasMany('Jurado', array(
             'local' => 'id_tipo',
             'foreign' => 'id_tipo_jurado'));

        $this->hasMany('MesaEntidadEducativa', array(
             'local' => 'id_tipo',
             'foreign' => 'id_tipo_jornada'));

        $this->hasMany('PerfilesPersona', array(
             'local' => 'id_tipo',
             'foreign' => 'id_tipo_perfil'));

        $this->hasMany('Persona', array(
             'local' => 'id_tipo',
             'foreign' => 'tipo_doc_id'));

        $this->hasMany('Votante', array(
             'local' => 'id_tipo',
             'foreign' => 'id_tipo_eleccion'));
    }
}