<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Votante', 'doctrine');

/**
 * BaseVotante
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_votante
 * @property integer $voto
 * @property timestamp $fecha_voto
 * @property integer $id_entidad_educativa
 * @property integer $id_mesa
 * @property integer $habilitado
 * @property integer $ingreso_votar
 * @property integer $id_tipo_eleccion
 * @property Tipo $Tipo
 * @property Persona $Persona
 * @property MesaEntidadEducativa $MesaEntidadEducativa
 * @property MesaEntidadEducativa $MesaEntidadEducativa_4
 * @property Doctrine_Collection $Candidato
 * 
 * @method integer              getIdVotante()              Returns the current record's "id_votante" value
 * @method integer              getVoto()                   Returns the current record's "voto" value
 * @method timestamp            getFechaVoto()              Returns the current record's "fecha_voto" value
 * @method integer              getIdEntidadEducativa()     Returns the current record's "id_entidad_educativa" value
 * @method integer              getIdMesa()                 Returns the current record's "id_mesa" value
 * @method integer              getHabilitado()             Returns the current record's "habilitado" value
 * @method integer              getIngresoVotar()           Returns the current record's "ingreso_votar" value
 * @method integer              getIdTipoEleccion()         Returns the current record's "id_tipo_eleccion" value
 * @method Tipo                 getTipo()                   Returns the current record's "Tipo" value
 * @method Persona              getPersona()                Returns the current record's "Persona" value
 * @method MesaEntidadEducativa getMesaEntidadEducativa()   Returns the current record's "MesaEntidadEducativa" value
 * @method MesaEntidadEducativa getMesaEntidadEducativa4()  Returns the current record's "MesaEntidadEducativa_4" value
 * @method Doctrine_Collection  getCandidato()              Returns the current record's "Candidato" collection
 * @method Votante              setIdVotante()              Sets the current record's "id_votante" value
 * @method Votante              setVoto()                   Sets the current record's "voto" value
 * @method Votante              setFechaVoto()              Sets the current record's "fecha_voto" value
 * @method Votante              setIdEntidadEducativa()     Sets the current record's "id_entidad_educativa" value
 * @method Votante              setIdMesa()                 Sets the current record's "id_mesa" value
 * @method Votante              setHabilitado()             Sets the current record's "habilitado" value
 * @method Votante              setIngresoVotar()           Sets the current record's "ingreso_votar" value
 * @method Votante              setIdTipoEleccion()         Sets the current record's "id_tipo_eleccion" value
 * @method Votante              setTipo()                   Sets the current record's "Tipo" value
 * @method Votante              setPersona()                Sets the current record's "Persona" value
 * @method Votante              setMesaEntidadEducativa()   Sets the current record's "MesaEntidadEducativa" value
 * @method Votante              setMesaEntidadEducativa4()  Sets the current record's "MesaEntidadEducativa_4" value
 * @method Votante              setCandidato()              Sets the current record's "Candidato" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Hender Orlando Puello Rincón
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVotante extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('votante');
        $this->hasColumn('id_votante', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('voto', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('fecha_voto', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_entidad_educativa', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_mesa', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('habilitado', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('ingreso_votar', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('id_tipo_eleccion', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tipo', array(
             'local' => 'id_tipo_eleccion',
             'foreign' => 'id_tipo'));

        $this->hasOne('Persona', array(
             'local' => 'id_votante',
             'foreign' => 'id_persona'));

        $this->hasOne('MesaEntidadEducativa', array(
             'local' => 'id_entidad_educativa',
             'foreign' => 'id_entidad_educativa'));

        $this->hasOne('MesaEntidadEducativa as MesaEntidadEducativa_4', array(
             'local' => 'id_mesa',
             'foreign' => 'id_mesa'));

        $this->hasMany('Candidato', array(
             'local' => 'id_votante',
             'foreign' => 'id_candidato'));
    }
}