# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        joaPolling - Administrador
    description:  Pagina para apoyar las elecciones de representantes en una entidad educativa.
    keywords:     votar, votacion, colegio, universidad, consejo academico, personero, penrsonerito, consejo estudiantil, representante docentes, representante estudiantes, elección, elecciones
    language:     es
    robots:       index, follow

  stylesheets:    [jquery.css, 960.min.css, selectmenu.css, main.css]

  javascripts:    [jquery.js, jqueryui.js, selectmenu.js, main.js]

  has_layout:     true
  layout:         backend
