<?php

/**
 * ArchivoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArchivoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArchivoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Archivo');
    }
    
    public function getFotos(){
        return ArchivoTable::getFotos1();
    }
    
    public static function getFotos1(){
        return ArchivosEntidadEducativaTable::getInstance()->findBy('id_tipo', 22);
    }
}