<?php

/**
 * ArchivosEntidadEducativaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArchivosEntidadEducativaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArchivosEntidadEducativaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ArchivosEntidadEducativa');
    }
    
    public static function getFotos(){
        return ArchivosEntidadEducativaTable::getInstance()->findBy('id_tipo_uso', 22);
    }
}