<?php

/**
 * CandidatoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CandidatoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CandidatoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Candidato');
    }
    
    /**
    * Return Candidatos según el tipo de elección
    * 
    * @param Tipo $tipoEleccion El tipo de elección
    */
    public static function getCandidatosEleccion(Tipo $tipoEleccion){
        return CandidatoTable::getInstance()
                ->createQuery('c')
                ->andWhere('c.id_tipo_eleccion = ?',$tipoEleccion->getIdTipo())
                ->orderBy('c.no ASC')
                ->addGroupBy('c.id_candidato')
                ->execute()
            ;
    }
}