<?php

/**
 * Candidato
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Candidato extends BaseCandidato
{
    public function getNombre(){
        return $this->getVotante()->getNombre();
    }
    public function getPersona(){
        return $this->getVotante()->getPersona();
    }
    public function getArchivo(){
        return $this->getArchivosEntidadEducativa()->getArchivo();
    }
}
