<?php

/**
 * CursosGradoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CursosGradoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CursosGradoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CursosGrado');
    }
    /**
     * Retorna el objeto si lo encuentra o NULL en caso contrario.
     *
     * @param Array array(id_curso => -1, id_grado => -1, id_entidad_educativa => -1)
     * @return object CursoGrado
     */
    public static function getCursoGrado($datos) {
        $c = CursosGradoTable::getInstance()->createQuery('c')
                ->andWhere('id_curso =?', $datos['id_curso'])
                ->andWhere('id_grado =?', $datos['id_grado'])
                ->andWhere('id_entidad_educativa =?', $datos['id_entidad_educativa'])
                ->fetchOne();
        return $c;
    }
}