<?php

/**
 * CursosGrado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Hender Orlando Puello Rincón
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CursosGrado extends BaseCursosGrado
{
    private $grado = NULL;
    private $entidadEducativa = NULL;
    
    function __construct($table = null, $isNewEntry = false) {
        parent::__construct($table, $isNewEntry);
    }
    public function getGrado(){
        if(is_null($this->grado)){
            $gee = GradoEntidadEducativaTable::getGradoEntidad(array('id_grado' => $this->getIdGrado(), 'id_entidad_educativa' => $this->getIdEntidadEducativa()));
            if($gee){
                $this->grado = $gee->getGrado();
            }
        }
        return $this->grado;
    }
    public function getEntidadEducativa(){
        if(is_null($this->entidadEducativa)){
            $gee = GradoEntidadEducativaTable::getGradoEntidad(array('id_grado' => $this->getIdGrado(), 'id_entidad_educativa' => $this->getIdEntidadEducativa()));
            if($gee){
                $this->entidadEducativa = $gee->getEntidadEducativa();
            }
        }
        return $this->entidadEducativa;
    }
    public function getNombre(){
        return $this->getGrado()->getAbreviatura().'-'.$this->getCurso()->getAbreviatura();
    }
}
