<?php

/**
 * EntidadEducativaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EntidadEducativaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EntidadEducativaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EntidadEducativa');
    }
    
    /**
     * Retorna el listado de personas que pertenecen a la Entidad Educativa con
     * sus perfiles
     *
     * @param Integer $id_entidad_educativa
     * @return Array 
     */
    public static function getPerfilesPersonasEntidadEducativa($id_entidad_educativa)
    {
        return PerfilesPersonaTable::getInstance()->findBy('id_entidad_educativa', $id_entidad_educativa);
    }
    
    /**
     * Retorna el administrador de la Entidad Educativa con
     * sus perfiles
     *
     * @param Integer $id_entidad_educativa
     * @return Array 
     */
    public static function getAdministradorEntidadEducativa($id_entidad_educativa)
    {
        $admin = NULL;
        foreach(EntidadEducativaTable::getPerfilesPersonasEntidadEducativa($id_entidad_educativa) as $personaEntidadEducativa){
            if($personaEntidadEducativa->getPersona()->hasTipo(4)){
                $admin = $personaEntidadEducativa->getPersona();
            }
        }
        return $admin;
    }
    public function getEntidadesEducativas(){
        return EntidadEducativaTable::getEntidadesEducativas1();
    }
    public static function getArrayEntidadesEducativas(){
        $ees = array();
        foreach(EntidadEducativaTable::getEntidadesEducativas1() as $ee){
            $ees[$ee->getIdEntidadEducativa()] = $ee->getAbreviatura();
        }
        return $ees;
    }
    public static function getEntidadesEducativas1(){
        $ees = EntidadEducativaTable::getInstance()->findAll();
        foreach($ees as $id => $ee){
            if($ee->getNombre() == 'joaPolling')
                unset($ees[$id]);
        }
        return $ees;
    }
}