<?php

/**
 * EntidadEducativa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EntidadEducativa extends BaseEntidadEducativa
{
    public function getUrlImagen($tipo_uso){
        $q = Doctrine_Core::getTable('ArchivosEntidadEducativa')
                ->createQuery('aee')
                ->leftJoin('aee.Tipo t')
                ->andWhere('t.nombre =? ',$tipo_uso)
                ->andWhere('aee.id_entidad_educativa =? ', $this->getIdEntidadEducativa())
                ->fetchOne();
        if($q)
            return $q->getArchivo()->getSrc();
        else
            return NULL;
    }
}
