<?php

/**
 * EstudianteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstudianteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstudianteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Estudiante');
    }
    /**
     * Retorna al estudiante buscado en un curso.
     *
     * @param char curso Curso donde buscar
     * @param int codigo Codigo del estudiante en el curso
     * @return object EstudianteTable
     */
    public static function getEstudianteCurso($id_curso_grado, $codigo)
    {
        return EstudianteTable::getInstance()->createQuery('e')
                ->andWhere('e.id_curso =? ', $id_curso_grado)
                ->andWhere('e.cod_curso =? ', $codigo)
                ->fetchOne();
    }
}