<?php

/**
 * Estudiante
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Estudiante extends BaseEstudiante
{
    public function getNombre() {
        return $this->getPersona()->getNombre();
    }
    /*
     * Retorna el votante
     * 
     * return Votante $votante
     */
    public function getVotante(){
        return $this->getPersona()->getVotante();
    }
    
    /*
     * Retorna el jurado
     * 
     * return Jurado $jurado
     */
    public function getJurado(){
        return $this->getPersona()->getJurado();
    }
    
    /*
     * Retorna la joranda del Estudiante
     * 
     * return Jurado $jurado
     */
    public function getJornada($nombre = false){
        if($nombre == true)
            return $this->getCursosGrado()->getGrado()->getTipo()->getNombre();
        return $this->getCursosGrado()->getGrado()->getIdTipo();
    }
    
    /*
     * Retorna el grado del Estudiante
     * 
     * return Jurado $jurado
     */
    public function getGrado($nombre = false){
        if($nombre == true)
            return $this->getCursosGrado()->getGrado()->getNombre();
        return $this->getCursosGrado()->getGrado();
    }
    
}
