<?php

/**
 * GradoEntidadEducativaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GradoEntidadEducativaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GradoEntidadEducativaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GradoEntidadEducativa');
    }

    /**
     * Retorna el objeto si lo encuentra o NULL en caso contrario.
     *
     * @param Array array(id_grado => '', id_entidad_educativa => '')
     * @return object GradoEntidadEducativa
     */
    public static function getGradoEntidad($datos) {
        $gee = GradoEntidadEducativaTable::getInstance()->createQuery()
                ->andWhere('id_grado =?', $datos['id_grado'])
                ->andWhere('id_entidad_educativa =?', $datos['id_entidad_educativa'])
                ->fetchOne();
        return $gee;
    }
}