<?php

/**
 * GrupoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GrupoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GrupoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Grupo');
    }
    
    public static function getGrupo($array) {
        if(is_array($array)){
            $q = GrupoTable::getInstance()->createQuery();
            foreach ($array as $i => $d){
                $q->andWhere($i.' =? ',$d);
            }
            return $q->fetchOne();
        }
        else
            return false;
    }
}