<?php

/**
 * Jurado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Jurado extends BaseJurado
{
    public function getNombre(){
        return $this->getPersona()->getNombre();
    }
    
    /*
     * Retorna el votante
     * 
     * return Votante $votante
     */
    public function getVotante(){
        $this->getPersona()->getVotante();
    }
    /*
     * Retorna el votante
     * 
     * return Votante $votante
     */
    public function getTipoEleccion($nombre = false){
        if($nombre)
            return $this->getVotante()->getTipo()->getNombre();
        return $this->getVotante()->getIdTipo();
    }
    
    /*
     * Retorna el estudiante
     * 
     * return Estudiante $estudiante
     */
    public function getEstudiante(){
        $this->getPersona()->getEstudiante();
    }
}
