<?php

/**
 * JuradoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JuradoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JuradoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Jurado');
    }
    
    public static function getJuradosEntidadEducativa($id_ee){
        $votantes = Doctrine_Query::create()
            ->from('Jurado j')
            ->leftJoin('j.Persona p')
            ->leftJoin('p.TipoPersona tp')
            ->andWhere('tp.id_entidad_educativa =?', $id_ee);
        return $votantes->execute();
    }
}