<?php

/**
 * MesaEntidadEducativa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Hender Orlando Puello Rincón
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MesaEntidadEducativa extends BaseMesaEntidadEducativa
{
    
    public function getNombreMesa(){
        return $this->getMesa()->getNombre();
    }
    public function getNombreEntidad(){
        return $this->getEntidadEducativa()->getNombre();
    }
    public function getJornada(){
        return TipoTable::getInstance()->findOneBy('id_tipo', $this->getIdTipoJornada());
    }
}
