<?php

/**
 * MesaEntidadEducativaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MesaEntidadEducativaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MesaEntidadEducativaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MesaEntidadEducativa');
    }
    
    /**
     * Retorna el objeto si lo encuentra o NULL en caso contrario.
     *
     * @param Array array(id_mesa => -1, abreviatura_entidad_educativa => '')
     * @return object GradoEntidadEducativa
     */
    public static function getMesaEntidad($datos) {
        $mee = MesaEntidadEducativaTable::getInstance()->createQuery('mee')
                ->leftJoin('mee.EntidadEducativa ee')
                ->leftJoin('mee.Mesa m')
                ->andWhere('m.id_mesa =?', $datos['id_mesa'])
                ->andWhere('ee.abreviatura =?', $datos['abreviatura_entidad_educativa'])
                ->fetchOne();
        return $mee;
    }
}