<?php

/**
 * PerfilesPersonaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PerfilesPersonaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PerfilesPersonaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PerfilesPersona');
    }
    public static function getPerfiles($idPersona, $idEntidadEducativa){
        $q = PerfilesPersonaTable::getInstance()->createQuery()
                ->andWhere('id_persona', $idPersona)
                ->andWhere('id_entidad_educativa',$idEntidadEducativa);
        return $q->execute();
    }
    
    public static function getPersonaPerfil($idPersona, $idEntidadEducativa, $idPerfil){
        $q = PerfilesPersonaTable::getInstance()->createQuery()
                ->andWhere('id_persona', $idPersona)
                ->andWhere('id_entidad_educativa',$idEntidadEducativa)
                ->andWhere('id_tipo_perfil',$idPerfil);
        return $q->fetchOne();
    }
}