<?php

/**
 * Votante
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Votante extends BaseVotante
{
    public function getNombre(){
        return $this->getPersona()->getNombre();
    }
    /*
     * Retorna la Mesa
     * 
     * return MesaEntidadEducativa $mesa
     */
    public function getMesa(){
        return MesaEntidadEducativaTable::getInstance()->createQuery()
                ->andWhere('id_entidad_educativa =? ', $this->getIdEntidadEducativa())
                ->andWhere('id_mesa =? ', $this->getIdMesa())
            ->fetchOne();
    }
    /*
     * Retorna el jurado
     * 
     * return Jurado $jurado
     */
    public function getJurado(){
        return $this->getPersona()->getJurado();
    }
    
    /*
     * Retorna el estudiante
     * 
     * return Estudiante $estudiante
     */
    public function getEstudiante(){
        return $this->getPersona()->getEstudiante();
    }
    
    /*
     * Retorna el mp,bre y el curso del votante
     * 
     * return Estudiante $estudiante
     */
    public function getNombreGrado(){
        $estudiante = EstudianteTable::getInstance()->find($this->getIdVotante());
        if(is_a($estudiante, 'Estudiante'))
            return $this->getPersona()->getNombre().' - '.$estudiante->getGrado()->getNombre();
        return false;
    }
    
    /*
     * Retorna la jornada del estudiante
     * 
     * return Estudiante $estudiante
     */
    public function getJornada($nombre = false){
        return $this->getPersona()->getJornada($nombre);
    }
    /*
     * Retorna si un votante pertenece a una entidad educativa
     * y da la opción de retornar un bool o un objeto
     * 
     * return Bool $este
     * return EntidadEducativa $entidadEducativa
     */
    public function isEntidadEducativa($id_entidad, $obj = false){
        return $this->getPersona()->isEntidadEducativa($id_entidad,$obj);
    }
}
