<?php

/**
 * VotanteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VotanteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VotanteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Votante');
    }
    
    public static function getVotantesArray($grado = false){
        $votantes = array('' => '');
        foreach(VotanteTable::getInstance()->findAll() as $votante){
            if($grado)
                $votantes[$votante->getIdVotante()] = $votante->getNombreGrado();
            else
                $votantes[$votante->getIdVotante()] = $votante->getNombre();
        }
        return $votantes;
    }
    
    public static function getVotantesEntidadEducativa($id_ee, $id_eleccion = false){
//        $votantes = VotanteTable::getInstance()->findAll();
//        if(!is_bool($id_eleccion)){
            $votantes = VotanteTable::getInstance()->createQuery()->where('id_tipo =?',$id_eleccion)->execute();
//        }
        foreach ($votantes as $id => $votante){
            if(!$votante->isEntidadEducativa($id_ee))
                unset ($votantes[$id]);
        }
        return $votantes;
//        $votantes = Doctrine_Query::create()
//            ->from('Votante v')
//            ->leftJoin('v.Persona p')
//            ->innerJoin('p.TipoPersona tp')
//            ->andWhere('tp.id_entidad_educativa =?', $id_ee);
//        if($query)
//            return $votantes->execute();
//        return $votantes;
    }
}